# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e72af8b39844daa3f563f268aa344359af1be69a6aac29031d30ae8074e52708ca0ad4733109295753a47edf153e2487c15be762ace1a45d40a223881d39f76e

test:
  secret_key_base: 74a9974a877499d75e40f26983a13c5fa2f126d8678ff6fdf277ad1aa5824c7fcce37f6b1464a8f06cf84f73da6e27b338a858e564243e5ead2f1537a90fe3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
